### ISSUE TITLE
I can't find some resource file.

### ISSUE THREAD

**Issue by p2ri** [Tastenkunst/brfv4_ane_examples#1]
Thank you for great project.

I'd like to use the brfv4_ane_examples. but I can't find two resources.

[Embed(source="../../../../bin/assets/brfv4_face_textures.jpeg")]
public static var textureFile : Class;
[Embed(source="../../../../bin/assets/brfv4_face_textures.txt", mimeType="application/octet-stream")]
public static var uvFile : Class;

Where can I find it?

**Comment by MarcelKlammer** [comment]
Damn. First day, first issue :D. I accidentally added the bin folder to gitignore. 
So this is fixed, I added bin/assets

**Comment by p2ri** [comment]
Thank you so much!!!
