### ISSUE TITLE
implemenation of API in sending data to 3rd party app

### ISSUE THREAD

**Issue by floatingworld3** [Tastenkunst/brfv4_ane_examples#10]
[html.txt](https://github.com/Tastenkunst/brfv4_ane_examples/files/2512723/html.txt)
I am attempting to create a websocket in order to  send position data of vertices  to my 3d app...using....

vectors: brfv4.__brf_get_opticalFlowPoints {
								return {
									x: Math.round(point[0]),
									y: Math.round(point[1])
								}

What should follow brfv4.__brf_get_opticalFlowPoints to return the set of vectors?

**Comment by MarcelKlammer** [comment]
Please open Javascript issues here: 
[https://github.com/Tastenkunst/brfv4_javascript_examples/issues](https://github.com/Tastenkunst/brfv4_javascript_examples/issues)

Also in the JS repo there is a more minimal examples in minimalWebcam.html

This might be easier for your purpose.
